server.port=8080
server.servlet.context-path=/api

# MySQL 8 Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Root@123$
spring.datasource.url=jdbc:mysql://myorg-database-1.cvaymsokwwek.ap-south-2.rds.amazonaws.com:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=iwC3UiMrx6ZRNX4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.max_allowed_packet=2000